include: package:flutter_lints/flutter.yaml

linter:
  rules:
  # Here you can turn individual rules on/off if you need exceptions.
  # For example:
  #   always_declare_return_types: false
  #   use_full_hex_values_for_flutter_colors: true
