name: linkcash_app
description: "make payment using link"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  lottie: ^3.1.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  cached_network_image: ^3.2.3
  sqflite: ^2.3.0
  table_calendar: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/images/